Repository obsidian-tools/obsidian-tools, pull requests merged in 2021-02, with the labels that each got.

#2 Update docs
  README.md
  package.json
  patches/@auto-it+npm+10.16.5.patch
  patches/@lerna+publish+4.0.0.patch
  resources/logo.svg
  yarn.lock
Labels: documentation

#4 Add auto plugin to readme
  README.md
Labels: documentation

#10 Fix manfest path and make zip a first class feature
  packages/auto-plugin-obsidian/README.md
  packages/auto-plugin-obsidian/src/index.ts
Labels: minor

#11 correct copy usage
  packages/auto-plugin-obsidian/src/index.ts
Labels: patch

#14 Add function to find vault from disk
  packages/obsidian-utils/src/index.ts
  packages/obsidian-utils/src/utils.ts
  packages/obsidian-utils/src/vault.ts
Labels: minor

#16 Update attribution, other small copy updates
  README.md
  packages/obsidian-utils/README.md
Labels: documentation

#19 Add typescript types to obsidian-utils
  packages/obsidian-utils/build.js
  packages/obsidian-utils/package.json
  packages/obsidian-utils/src/install.ts
  packages/obsidian-utils/src/readFromDisk.ts
  packages/obsidian-utils/src/registry.ts
  packages/obsidian-utils/src/utils.ts
  packages/obsidian-utils/tsconfig.json
  yarn.lock
Labels: minor

#20 Fix `obsidian-utils` types
  packages/obsidian-utils/tsconfig.json
Labels: patch

#21 Export utils, update findVault to optionally take a vaultPath
  packages/obsidian-utils/src/index.ts
  packages/obsidian-utils/src/vault.ts
Labels: minor

#22 Pass along vault open state from obsidian config
  packages/obsidian-utils/src/vault.ts
Labels: minor

#23 Add isVault util, rename failIfNot for clarity
  packages/obsidian-utils/src/install.ts
  packages/obsidian-utils/src/readFromDisk.ts
  packages/obsidian-utils/src/utils.ts
  packages/obsidian-utils/src/vault.ts
Labels: minor

#25 Set node compat for utils to node v12
  packages/obsidian-utils/build.js
  packages/obsidian-utils/package.json
Labels: patch

#26 Add notification when update is available
  .vscode/launch.json
  packages/obsidian-plugin-cli/package.json
  packages/obsidian-plugin-cli/src/hooks/update-notifier.ts
  yarn.lock
Labels: minor

#28 Update docs
  packages/obsidian-utils/README.md
  packages/obsidian-utils/docs/classes/plugin.pluginregistry.md
  packages/obsidian-utils/docs/classes/plugin_registry.pluginregistry.md
  packages/obsidian-utils/docs/interfaces/plugin.installedplugininfo.md
  packages/obsidian-utils/docs/interfaces/plugin.pluginregistrydata.md
  packages/obsidian-utils/docs/interfaces/plugin.pluginregistryrecord.md
  packages/obsidian-utils/docs/interfaces/plugin_local.installedplugininfo.md
  packages/obsidian-utils/docs/interfaces/plugin_registry.pluginregistrydata.md
  packages/obsidian-utils/docs/interfaces/plugin_registry.pluginregistryrecord.md
  packages/obsidian-utils/docs/modules/index.md
  packages/obsidian-utils/docs/modules/log.md
  packages/obsidian-utils/docs/modules/plugin.md
  packages/obsidian-utils/docs/modules/plugin_install.md
  packages/obsidian-utils/docs/modules/plugin_local.md
  packages/obsidian-utils/docs/modules/plugin_utils.md
  packages/obsidian-utils/docs/modules/types.md
  packages/obsidian-utils/docs/modules/utils.md
  packages/obsidian-utils/docs/modules/vault.md
  packages/obsidian-utils/package.json
  packages/obsidian-utils/src/index.ts
Labels: documentation

#29 Update obsidian-plugin-cli to use new utils
  packages/obsidian-plugin-cli/package.json
  packages/obsidian-plugin-cli/src/commands/dev.ts
  yarn.lock
Labels: minor

#30 Add hot reloading to dev build
  .gitattributes
  packages/obsidian-plugin-cli/package.json
  packages/obsidian-plugin-cli/src/commands/dev.ts
  packages/obsidian-utils/docs/modules/log.md
  packages/obsidian-utils/docs/modules/plugin.md
  packages/obsidian-utils/docs/modules/plugin_local.md
  packages/obsidian-utils/src/log.ts
  packages/obsidian-utils/src/plugin/local.ts
Labels: minor

#33 Fix esbuild error
  packages/obsidian-plugin-cli/src/build.ts
Labels: patch

#34 Ensure entrypoint gets properly passed
  packages/obsidian-plugin-cli/src/config.ts
Labels: patch

#36 improve instructions for enabling hot reload plugin
  packages/obsidian-plugin-cli/src/commands/dev.ts
Labels: patch

#35 Minify output of "obsidian-plugin build"
  packages/obsidian-plugin-cli/src/commands/build.ts
Labels: patch
